services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: litdev
      POSTGRES_PASSWORD: litdev
      POSTGRES_DB: lit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
volumes:
  postgres_data: